Repository winnipegfir/ZWG-Enhanced-Sector-File, pull requests merged in 2022-02, with the labels that each got.

#4 Updated Terminal ASR
  .gitattributes
  .vscode/settings.json
  CZWG/ASR/Terminal.asr
Labels: enhancement, removed

#8 Add PR label reminder
  README.md
Labels: enhancement

#17 Fix Euroscope auto updating
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  README.md
  SectorFileProviderDescriptor.txt
Labels: bug
